### PR TITLE
Update client go

### LINKED ISSUE #129: kubectl buildkit create fails with no Auth Provider found for name "azure" error
**What steps did you take and what happened**
Attempted to create a buildkit instance as described in example on a cluster using Azure authentication.
**What did you expect to happen**

The command to succeed. Kubectl commands have no problem using the azure provider.

**Environment Details:**

- kubectl buildkit version : `0.1.5`
- Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```
 
- Where are you running kubernetes: Azure via cluster-api
- Container Runtime and version: Containerd
``` 
Client:
  Version:  v1.6.0
  Revision: 39259a8f35919a0d02c9ecc2871ddd6ccf6a7c6e
  Go version: go1.17.2

Server:
  Version:  v1.6.0
  Revision: 39259a8f35919a0d02c9ecc2871ddd6ccf6a7c6e
  UUID: f43ebc8f-48e8-41e3-a161-457e414ac4dc
```

**Builder Logs**
N/A

**Dockerfile**
N/A

**Vote on this request**

This is an invitation to the community to vote on issues.  Use the "smiley face" up to the right of this comment to vote.

- :+1: "I would like to see this bug fixed as soon as possible"
- :-1: "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by gnadaban**
This PR updates the Kubernetes client version and includes all auth plugins for the Kubernetes Go client to support Azure clusters.

Fixes #129

### CODE REVIEW

**Comment by dhiltgen** [comment]
Thanks for the contribution!  The change LGTM.

We had a glitch in our CI system for one of the steps.  If you can rebase, it should pass the CI tests.  Once you sign the contributor agreement we can get this merged.

**Comment by gnadaban** [comment]
Sounds good @dhiltgen 👍🏼 , rebased as requested.

**Comment by gnadaban** [comment]
@dhiltgen , I've signed the contributor agreement, can you please re:re?

**Comment by dhiltgen** [comment]
LGTM

**Comment by gnadaban** [comment]
Hey @dhiltgen , do you think you could do a release soon so that I can install this with Homebrew?

**Pull request merged**
